"""Add supplier details to Purchase model

Revision ID: 67eba856799a
Revises: 9adc38319639
Create Date: 2024-09-02 14:05:57.392979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67eba856799a'
down_revision = '9adc38319639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('supplier_address')
        batch_op.drop_column('supplier_contact')
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###
