"""Sales table updated

Revision ID: 6897737310dd
Revises: f4ef4ff6a677
Create Date: 2024-09-02 23:18:45.763254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6897737310dd'
down_revision = 'f4ef4ff6a677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.Integer(), nullable=False))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('purchase_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_no', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.String(length=200), nullable=True))
        batch_op.alter_column('sales_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('sales_quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('customer_address')
        batch_op.drop_column('contact_no')
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('purchase_quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
